///**
//*****************************************************************************
//**
//**  File        : sysmem.c
//**
//**  Author	    : Auto-generated by STM32CubeIDE
//**
//**  Abstract    : STM32CubeIDE Minimal System Memory calls file
//**
//** 		          For more information about which c-functions
//**                need which of these lowlevel functions
//**                please consult the Newlib libc-manual
//**
//**  Environment : STM32CubeIDE MCU
//**
//**  Distribution: The file is distributed as is, without any warranty
//**                of any kind.
//**
//*****************************************************************************
//**
//** <h2><center>&copy; COPYRIGHT(c) 2018 STMicroelectronics</center></h2>
//**
//** Redistribution and use in source and binary forms, with or without modification,
//** are permitted provided that the following conditions are met:
//**   1. Redistributions of source code must retain the above copyright notice,
//**      this list of conditions and the following disclaimer.
//**   2. Redistributions in binary form must reproduce the above copyright notice,
//**      this list of conditions and the following disclaimer in the documentation
//**      and/or other materials provided with the distribution.
//**   3. Neither the name of STMicroelectronics nor the names of its contributors
//**      may be used to endorse or promote products derived from this software
//**      without specific prior written permission.
//**
//** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//** AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//** DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
//** FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//** DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
//** SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//** CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//** OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
//** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//**
//**
//*****************************************************************************
//*/
//
///* Includes */
//#include <errno.h>
//#include <stdio.h>
//
///* Variables */
//extern int errno;
//register char * stack_ptr asm("sp");
//
///* Functions */
//
///**
// _sbrk
// Increase program data space. Malloc and related functions depend on this
//**/
//void * _sbrk(int incr)
//{
//	extern char end asm("end");
//	static char *heap_end;
//	char *prev_heap_end;
//
//	if (heap_end == 0)
//		heap_end = &end;
//
//	prev_heap_end = heap_end;
//	if (heap_end + incr > stack_ptr)
//	{
//		errno = ENOMEM;
//		return (void *) -1;
//	}
//
//	heap_end += incr;
//
//	return (void *) prev_heap_end;
//}
/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}
